# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-18 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hacks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('descreption', models.TextField()),
                ('image', models.FileField(upload_to='', verbose_name='File name ')),
                ('theme', models.CharField(max_length=350)),
            ],
            options={
                'ordering': ('date_start',),
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=250)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hacks.Event')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('participant',),
            },
        ),
        migrations.CreateModel(
            name='WorkGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(verbose_name='Valid')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hacks.Event')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pilot',
            name='city',
        ),
        migrations.AddField(
            model_name='pilot',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hacks.Pilot'),
        ),
    ]
