# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-18 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0002_auto_20180518_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manual_validation',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
