# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-18 13:32
from __future__ import unicode_literals

import datas.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('path', models.FileField(upload_to='', verbose_name='File ')),
                ('forma', models.CharField(max_length=10)),
                ('uploaddate', models.DateField(blank=True, default=datetime.date.today)),
                ('external', models.BooleanField()),
                ('tags', models.ManyToManyField(to='datas.Tag')),
                ('uploaduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=250)),
                ('date_birth', models.DateField(blank=True, default=datetime.date.today)),
                ('imgpath', models.ImageField(default='user_avatar.png', upload_to=datas.models.scramble_file_name, verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1500)),
                ('provider', models.CharField(max_length=500)),
                ('usage', models.CharField(max_length=500)),
                ('accepted', models.CharField(default='False', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.AddField(
            model_name='tag',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datas.Category'),
        ),
    ]
