# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-18 13:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hacks', '0002_auto_20180518_1545'),
        ('datas', '0002_auto_20180518_1532'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlipCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typecard', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('path', models.FileField(upload_to='', verbose_name='image')),
                ('language', models.ManyToManyField(to='datas.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hackproces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hacks.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='', verbose_name='image')),
                ('fileformat', models.CharField(max_length=55)),
                ('thumbnail', models.CharField(max_length=5)),
                ('public', models.CharField(default='False', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=10)),
                ('corevalue', models.TextField()),
                ('datasource', models.TextField()),
                ('contactinfo', models.TextField()),
                ('created', models.DateField(default=datetime.date.today)),
                ('defenition', models.TextField()),
                ('files', models.ManyToManyField(to='tools.ProjectFiles')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hacks.WorkGroups')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AlterModelOptions(
            name='outil',
            options={'verbose_name_plural': 'Tools'},
        ),
        migrations.AddField(
            model_name='outil',
            name='categorys',
            field=models.CharField(default='learn', help_text='Please select the correct category of tool', max_length=10, verbose_name='Category '),
        ),
        migrations.AlterField(
            model_name='outil',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='outil',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tool name '),
        ),
        migrations.AddField(
            model_name='hackproces',
            name='outil_used',
            field=models.ManyToManyField(to='tools.Outil'),
        ),
    ]
